{{ if .Values.host }}
apiVersion: {{ include "capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "ui-base.name" . }}
  labels:
    {{ include "ui-base.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
{{ include "ingress.backend" (dict
     "serviceName" (printf "%s-oauth2-proxy" .Release.Name )
     "servicePort" (index .Values "oauth2-proxy" "service" "portNumber")
     "context" $
) | nindent 14 }}
{{ end }}
