apiVersion: v1
kind: Service
metadata:
    name: {{ include "ui-base.name" . }}
    namespace: {{ .Release.Namespace }}
spec:
    type: ClusterIP
    selector:
        app: {{ include "ui-base.name" . }}
    ports:
    - port: 80
      targetPort: {{ .Values.ui.port }}
