apiVersion: v2
name: visr
description: ViSR UI
type: application
version: 0.1.8 # Bumped by CI job
appVersion: "0.1.8" # Bumped by CI job

dependencies:
  - name: ui-base
    repository: "file://../../../helm/"
    version: 0.1.0
